### PR TITLE
Work Submission Report Project 4

### PR DESCRIPTION
**Pull request by abstrekt**
Work report submission for GSoC 2020 for Project 4.

### CODE REVIEW

**Comment by abstrekt** [comment]
@nitin10s @devl0rd @tachyons @satu0king  please review

**Review by nitin10s — COMMENTED** [review]
This looks great. Small additions:

1. Please include a section of your learnings and experience.
2. Please include a section of Future developments that could list anything close to your work that you didn't work on but could further be taken up by future developers [along with a brief description of what you tried that didn't work in case you tried]
3. Please fix the typos.

Everything else looks great!

**Comment by abstrekt** [comment]
@nitin10s  I have added them please give a final review

**Review by nitin10s — APPROVED** [review]

**Comment by nitin10s** [comment]
@tachyons

**Pull request merged**
