### PR TITLE
Fix #130: contact us form is accepting empty feedbacks .

### LINKED ISSUE #130: contact us form is accepting empty feedbacks .
The contact us form sending data even when the fields are empty. all the form fields should have a validator which validates if empty .

ezgif com-gif-maker(1)

### PR DESCRIPTION
**Pull request by subhamkumarr**
## Description:
The contact form was used to submit even when no inputs were entered. After making some changes, it now requires input before allowing submission

### Before:
https://www.loom.com/share/4eb68bd9937a4443858c6f5ab41bdde9?sid=9c67844f-caf7-48fa-9bd4-dc4c3d5c159f

### After:
https://www.loom.com/share/1265b4c8f19549a09b6d7777b9398ea3?sid=7c158744-d62d-4f69-9bff-9625421bd929

### CODE REVIEW

**Comment by subhamkumarr** [comment]
@tanmoysrt Sir, could you please review this PR

**Comment by tachyons** [comment]
Please do not make changes on submodule. Any changes on theme need to be done at the upstream repository

**Comment by subhamkumarr** [comment]
@tachyons, then how can I fix this issue? To solve this problem, I need to make changes in `themes/layouts/contact/list.html`. If there is another way to resolve this, please let me know. I need to fix this issue.

**Comment by tachyons** [comment]
You can make the changes to the upstream theme

**Comment by subhamkumarr** [comment]
@tachyons, where can I get the `upstream theme` in the blog repository?

**Comment by subhamkumarr** [comment]
@tachyons 
image
are you talking about this? I need to commit in this upstream?

**Pull request closed without merging**
