### PR TITLE
project 4 1st phase evaluation blog

### PR DESCRIPTION
**Pull request by abstrekt**

### CODE REVIEW

**Comment by abstrekt** [comment]
@tachyons @nitin10s  is this okay?

**Comment by abstrekt** [comment]
1st and 2nd phase both blogs are here i hope that's okay?

**Comment by abstrekt** [comment]
i was having some trouble with the upstream

**Comment by tachyons** [comment]
resolve conflicts please

**Comment by abstrekt** [comment]
sorry, didn't saw it,  fixed! @tachyons

**Pull request merged**
