### PR TITLE
Navbar Enhanced

### LINKED ISSUE #87: Navbar Size
* Problem Statement
The size of the navbar is too large. I will make it small and also add icons on menu bar links.

### PR DESCRIPTION
**Pull request by vedant-jain03**
Screenshot (42)

Enhancement:
1. Remove Home Button
2. Resize the logo to 70%
3. Hover effect changed to green theme color background

fixes #87

### CODE REVIEW

**Comment by vedant-jain03** [comment]
@nitin10s @ShreyaPrasad1209 @pavanjoshi914 please review

**Review by nitin10s — CHANGES_REQUESTED** [review]
Contact button should be kept as previous only, just change the hover color to theme green

**Review by vedant-jain03 — COMMENTED** [review]
Resolved

**Comment by nitin10s** [comment]
Please update the screenshots as well

**Comment by vedant-jain03** [comment]
> Please update the screenshots as well

Screenshot (45)

@nitin10s Here is sample ss, hover on contact turn green as requested!

**Review by ShreyaPrasad1209 — APPROVED** [review]
LGTM, @nitin10s what do you think?

**Comment by vedant-jain03** [comment]
@nitin10s Please review!

**Review by nitin10s — APPROVED** [review]

**Comment by nitin10s** [comment]
@satu0king merge please

**Pull request merged**
